# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .app import *
from .cert import *
from .get_app import *
from .get_cert import *
from .get_ip import *
from .get_volume import *
from .ip import *
from .machine import *
from .provider import *
from .volume import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import ediri_fly.config as __config
    config = __config
else:
    config = _utilities.lazy_import('ediri_fly.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "fly",
  "mod": "index/app",
  "fqn": "ediri_fly",
  "classes": {
   "fly:index/app:App": "App"
  }
 },
 {
  "pkg": "fly",
  "mod": "index/cert",
  "fqn": "ediri_fly",
  "classes": {
   "fly:index/cert:Cert": "Cert"
  }
 },
 {
  "pkg": "fly",
  "mod": "index/ip",
  "fqn": "ediri_fly",
  "classes": {
   "fly:index/ip:Ip": "Ip"
  }
 },
 {
  "pkg": "fly",
  "mod": "index/machine",
  "fqn": "ediri_fly",
  "classes": {
   "fly:index/machine:Machine": "Machine"
  }
 },
 {
  "pkg": "fly",
  "mod": "index/volume",
  "fqn": "ediri_fly",
  "classes": {
   "fly:index/volume:Volume": "Volume"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "fly",
  "token": "pulumi:providers:fly",
  "fqn": "ediri_fly",
  "class": "Provider"
 }
]
"""
)
