# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'MachineMountArgs',
    'MachineMountArgsDict',
    'MachineServiceArgs',
    'MachineServiceArgsDict',
    'MachineServicePortArgs',
    'MachineServicePortArgsDict',
]

class MachineMountArgsDict(TypedDict):
    path: pulumi.Input[_builtins.str]
    """
    Path for volume to be mounted on vm, ex: `/data`
    """
    volume: pulumi.Input[_builtins.str]
    """
    ID of volume
    """

@pulumi.input_type
class MachineMountArgs:
    def __init__(__self__, *,
                 path: pulumi.Input[_builtins.str],
                 volume: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.str] path: Path for volume to be mounted on vm, ex: `/data`
        :param pulumi.Input[_builtins.str] volume: ID of volume
        """
        pulumi.set(__self__, "path", path)
        pulumi.set(__self__, "volume", volume)

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Input[_builtins.str]:
        """
        Path for volume to be mounted on vm, ex: `/data`
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter
    def volume(self) -> pulumi.Input[_builtins.str]:
        """
        ID of volume
        """
        return pulumi.get(self, "volume")

    @volume.setter
    def volume(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "volume", value)


class MachineServiceArgsDict(TypedDict):
    internal_port: pulumi.Input[_builtins.int]
    """
    Port the machine listens on
    """
    ports: pulumi.Input[Sequence[pulumi.Input['MachineServicePortArgsDict']]]
    """
    How the port is exposed
    """
    protocol: pulumi.Input[_builtins.str]
    """
    `udp` or `tcp`
    """

@pulumi.input_type
class MachineServiceArgs:
    def __init__(__self__, *,
                 internal_port: pulumi.Input[_builtins.int],
                 ports: pulumi.Input[Sequence[pulumi.Input['MachineServicePortArgs']]],
                 protocol: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.int] internal_port: Port the machine listens on
        :param pulumi.Input[Sequence[pulumi.Input['MachineServicePortArgs']]] ports: How the port is exposed
        :param pulumi.Input[_builtins.str] protocol: `udp` or `tcp`
        """
        pulumi.set(__self__, "internal_port", internal_port)
        pulumi.set(__self__, "ports", ports)
        pulumi.set(__self__, "protocol", protocol)

    @_builtins.property
    @pulumi.getter(name="internalPort")
    def internal_port(self) -> pulumi.Input[_builtins.int]:
        """
        Port the machine listens on
        """
        return pulumi.get(self, "internal_port")

    @internal_port.setter
    def internal_port(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "internal_port", value)

    @_builtins.property
    @pulumi.getter
    def ports(self) -> pulumi.Input[Sequence[pulumi.Input['MachineServicePortArgs']]]:
        """
        How the port is exposed
        """
        return pulumi.get(self, "ports")

    @ports.setter
    def ports(self, value: pulumi.Input[Sequence[pulumi.Input['MachineServicePortArgs']]]):
        pulumi.set(self, "ports", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> pulumi.Input[_builtins.str]:
        """
        `udp` or `tcp`
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "protocol", value)


class MachineServicePortArgsDict(TypedDict):
    end_port: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    For a port range, the last port to listen on
    """
    force_https: NotRequired[pulumi.Input[Optional[_builtins.bool]]]
    """
    Automatically redirect to HTTPS on "http" handler
    """
    handlers: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]]
    """
    How the edge should process requests; ex empty, or `tls` to attach app's certificate
    """
    port: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Mapped external port number, either `port` or `start_port` and `end_port` must be set.
    """
    start_port: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    For a port range, the first port to listen on.
    """

@pulumi.input_type
class MachineServicePortArgs:
    def __init__(__self__, *,
                 end_port: pulumi.Input[Optional[_builtins.int]] = None,
                 force_https: pulumi.Input[Optional[_builtins.bool]] = None,
                 handlers: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 port: pulumi.Input[Optional[_builtins.int]] = None,
                 start_port: pulumi.Input[Optional[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.int] end_port: For a port range, the last port to listen on
        :param pulumi.Input[_builtins.bool] force_https: Automatically redirect to HTTPS on "http" handler
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] handlers: How the edge should process requests; ex empty, or `tls` to attach app's certificate
        :param pulumi.Input[_builtins.int] port: Mapped external port number, either `port` or `start_port` and `end_port` must be set.
        :param pulumi.Input[_builtins.int] start_port: For a port range, the first port to listen on.
        """
        if end_port is not None:
            pulumi.set(__self__, "end_port", end_port)
        if force_https is not None:
            pulumi.set(__self__, "force_https", force_https)
        if handlers is not None:
            pulumi.set(__self__, "handlers", handlers)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if start_port is not None:
            pulumi.set(__self__, "start_port", start_port)

    @_builtins.property
    @pulumi.getter(name="endPort")
    def end_port(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        For a port range, the last port to listen on
        """
        return pulumi.get(self, "end_port")

    @end_port.setter
    def end_port(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "end_port", value)

    @_builtins.property
    @pulumi.getter(name="forceHttps")
    def force_https(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Automatically redirect to HTTPS on "http" handler
        """
        return pulumi.get(self, "force_https")

    @force_https.setter
    def force_https(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "force_https", value)

    @_builtins.property
    @pulumi.getter
    def handlers(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        How the edge should process requests; ex empty, or `tls` to attach app's certificate
        """
        return pulumi.get(self, "handlers")

    @handlers.setter
    def handlers(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "handlers", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Mapped external port number, either `port` or `start_port` and `end_port` must be set.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "port", value)

    @_builtins.property
    @pulumi.getter(name="startPort")
    def start_port(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        For a port range, the first port to listen on.
        """
        return pulumi.get(self, "start_port")

    @start_port.setter
    def start_port(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "start_port", value)


