version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/provider"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "sunday"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/provider/shim"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "sunday"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/sdk"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
