// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Fly
{
    public static class GetCert
    {
        public static Task<GetCertResult> InvokeAsync(GetCertArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCertResult>("fly:index/getCert:getCert", args ?? new GetCertArgs(), options.WithDefaults());

        public static Output<GetCertResult> Invoke(GetCertInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCertResult>("fly:index/getCert:getCert", args ?? new GetCertInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCertArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The App this resource will be created in
        /// </summary>
        [Input("app", required: true)]
        public string App { get; set; } = null!;

        [Input("hostname", required: true)]
        public string Hostname { get; set; } = null!;

        public GetCertArgs()
        {
        }
        public static new GetCertArgs Empty => new GetCertArgs();
    }

    public sealed class GetCertInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The App this resource will be created in
        /// </summary>
        [Input("app", required: true)]
        public Input<string> App { get; set; } = null!;

        [Input("hostname", required: true)]
        public Input<string> Hostname { get; set; } = null!;

        public GetCertInvokeArgs()
        {
        }
        public static new GetCertInvokeArgs Empty => new GetCertInvokeArgs();
    }


    [OutputType]
    public sealed class GetCertResult
    {
        /// <summary>
        /// The App this resource will be created in
        /// </summary>
        public readonly string App;
        public readonly bool Check;
        public readonly string DnsValidationHostname;
        public readonly string DnsValidationInstructions;
        public readonly string DnsValidationTarget;
        public readonly string Hostname;
        /// <summary>
        /// A fly-generated ID
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetCertResult(
            string app,

            bool check,

            string dnsValidationHostname,

            string dnsValidationInstructions,

            string dnsValidationTarget,

            string hostname,

            string id)
        {
            App = app;
            Check = check;
            DnsValidationHostname = dnsValidationHostname;
            DnsValidationInstructions = dnsValidationInstructions;
            DnsValidationTarget = dnsValidationTarget;
            Hostname = hostname;
            Id = id;
        }
    }
}
