// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Fly
{
    /// <summary>
    /// Fly ip resource
    /// 
    /// ## Example Usage
    /// 
    /// ## Import
    /// 
    /// &lt;break&gt;&lt;break&gt;```sh&lt;break&gt; $ pulumi import fly:index/ip:Ip exampleIp &lt;app_id&gt;,&lt;ip_address&gt; &lt;break&gt;```&lt;break&gt;&lt;break&gt;
    /// </summary>
    [FlyResourceType("fly:index/ip:Ip")]
    public partial class Ip : global::Pulumi.CustomResource
    {
        /// <summary>
        /// IP address
        /// </summary>
        [Output("address")]
        public Output<string> Address { get; private set; } = null!;

        /// <summary>
        /// Name of app to attach to
        /// </summary>
        [Output("app")]
        public Output<string> App { get; private set; } = null!;

        /// <summary>
        /// region
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// v4 or v6
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a Ip resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Ip(string name, IpArgs args, CustomResourceOptions? options = null)
            : base("fly:index/ip:Ip", name, args ?? new IpArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Ip(string name, Input<string> id, IpState? state = null, CustomResourceOptions? options = null)
            : base("fly:index/ip:Ip", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/dirien/pulumi-fly",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Ip resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Ip Get(string name, Input<string> id, IpState? state = null, CustomResourceOptions? options = null)
        {
            return new Ip(name, id, state, options);
        }
    }

    public sealed class IpArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of app to attach to
        /// </summary>
        [Input("app", required: true)]
        public Input<string> App { get; set; } = null!;

        /// <summary>
        /// region
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// v4 or v6
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public IpArgs()
        {
        }
        public static new IpArgs Empty => new IpArgs();
    }

    public sealed class IpState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// IP address
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        /// <summary>
        /// Name of app to attach to
        /// </summary>
        [Input("app")]
        public Input<string>? App { get; set; }

        /// <summary>
        /// region
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// v4 or v6
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public IpState()
        {
        }
        public static new IpState Empty => new IpState();
    }
}
