// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fly

import (
	"context"
	"reflect"

	"github.com/dirien/pulumi-fly/sdk/go/fly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupIp(ctx *pulumi.Context, args *LookupIpArgs, opts ...pulumi.InvokeOption) (*LookupIpResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupIpResult
	err := ctx.Invoke("fly:index/getIp:getIp", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIp.
type LookupIpArgs struct {
	// The App this resource will be created in
	App string `pulumi:"app"`
	// A fly-generated ID
	Id string `pulumi:"id"`
}

// A collection of values returned by getIp.
type LookupIpResult struct {
	// Empty if using `sharedV4`
	Address string `pulumi:"address"`
	// The App this resource will be created in
	App string `pulumi:"app"`
	// A fly-generated ID
	Id string `pulumi:"id"`
	// Fly region, ex `ord`, `sin`, `mad`
	Region string `pulumi:"region"`
	// `v4`, `v6`, or `privateV6`
	Type string `pulumi:"type"`
}

func LookupIpOutput(ctx *pulumi.Context, args LookupIpOutputArgs, opts ...pulumi.InvokeOption) LookupIpResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupIpResultOutput, error) {
			args := v.(LookupIpArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("fly:index/getIp:getIp", args, LookupIpResultOutput{}, options).(LookupIpResultOutput), nil
		}).(LookupIpResultOutput)
}

// A collection of arguments for invoking getIp.
type LookupIpOutputArgs struct {
	// The App this resource will be created in
	App pulumi.StringInput `pulumi:"app"`
	// A fly-generated ID
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupIpOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpArgs)(nil)).Elem()
}

// A collection of values returned by getIp.
type LookupIpResultOutput struct{ *pulumi.OutputState }

func (LookupIpResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpResult)(nil)).Elem()
}

func (o LookupIpResultOutput) ToLookupIpResultOutput() LookupIpResultOutput {
	return o
}

func (o LookupIpResultOutput) ToLookupIpResultOutputWithContext(ctx context.Context) LookupIpResultOutput {
	return o
}

// Empty if using `sharedV4`
func (o LookupIpResultOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpResult) string { return v.Address }).(pulumi.StringOutput)
}

// The App this resource will be created in
func (o LookupIpResultOutput) App() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpResult) string { return v.App }).(pulumi.StringOutput)
}

// A fly-generated ID
func (o LookupIpResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpResult) string { return v.Id }).(pulumi.StringOutput)
}

// Fly region, ex `ord`, `sin`, `mad`
func (o LookupIpResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpResult) string { return v.Region }).(pulumi.StringOutput)
}

// `v4`, `v6`, or `privateV6`
func (o LookupIpResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIpResultOutput{})
}
