// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fly

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-fly/sdk/go/fly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "fly:index/app:App":
		r = &App{}
	case "fly:index/cert:Cert":
		r = &Cert{}
	case "fly:index/ip:Ip":
		r = &Ip{}
	case "fly:index/machine:Machine":
		r = &Machine{}
	case "fly:index/volume:Volume":
		r = &Volume{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:fly" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"fly",
		"index/app",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fly",
		"index/cert",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fly",
		"index/ip",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fly",
		"index/machine",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"fly",
		"index/volume",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"fly",
		&pkg{version},
	)
}
