// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fly

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Fly machine resource
//
// ## Example Usage
//
// ## Import
//
// <break><break>```sh<break> $ pulumi import fly:index/machine:Machine exampleMachine <app_id>,<machine_id> <break>```<break><break>
type Machine struct {
	pulumi.CustomResourceState

	// fly app
	App pulumi.StringOutput `pulumi:"app"`
	// cmd
	Cmds pulumi.StringArrayOutput `pulumi:"cmds"`
	// cpu count
	Cpus pulumi.IntOutput `pulumi:"cpus"`
	// cpu type
	Cputype pulumi.StringOutput `pulumi:"cputype"`
	// image entrypoint
	Entrypoints pulumi.StringArrayOutput `pulumi:"entrypoints"`
	// Optional environment variables, keys and values must be strings
	Env pulumi.StringMapOutput `pulumi:"env"`
	// exec command
	Execs pulumi.StringArrayOutput `pulumi:"execs"`
	// docker image
	Image pulumi.StringOutput `pulumi:"image"`
	// memory mb
	Memorymb pulumi.IntOutput `pulumi:"memorymb"`
	// Volume mounts
	Mounts MachineMountArrayOutput `pulumi:"mounts"`
	// machine name
	Name pulumi.StringOutput `pulumi:"name"`
	// Private IP
	Privateip pulumi.StringOutput `pulumi:"privateip"`
	// machine region
	Region pulumi.StringOutput `pulumi:"region"`
	// services
	Services MachineServiceArrayOutput `pulumi:"services"`
}

// NewMachine registers a new resource with the given unique name, arguments, and options.
func NewMachine(ctx *pulumi.Context,
	name string, args *MachineArgs, opts ...pulumi.ResourceOption) (*Machine, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.App == nil {
		return nil, errors.New("invalid value for required argument 'App'")
	}
	if args.Image == nil {
		return nil, errors.New("invalid value for required argument 'Image'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource Machine
	err := ctx.RegisterResource("fly:index/machine:Machine", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMachine gets an existing Machine resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMachine(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MachineState, opts ...pulumi.ResourceOption) (*Machine, error) {
	var resource Machine
	err := ctx.ReadResource("fly:index/machine:Machine", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Machine resources.
type machineState struct {
	// fly app
	App *string `pulumi:"app"`
	// cmd
	Cmds []string `pulumi:"cmds"`
	// cpu count
	Cpus *int `pulumi:"cpus"`
	// cpu type
	Cputype *string `pulumi:"cputype"`
	// image entrypoint
	Entrypoints []string `pulumi:"entrypoints"`
	// Optional environment variables, keys and values must be strings
	Env map[string]string `pulumi:"env"`
	// exec command
	Execs []string `pulumi:"execs"`
	// docker image
	Image *string `pulumi:"image"`
	// memory mb
	Memorymb *int `pulumi:"memorymb"`
	// Volume mounts
	Mounts []MachineMount `pulumi:"mounts"`
	// machine name
	Name *string `pulumi:"name"`
	// Private IP
	Privateip *string `pulumi:"privateip"`
	// machine region
	Region *string `pulumi:"region"`
	// services
	Services []MachineService `pulumi:"services"`
}

type MachineState struct {
	// fly app
	App pulumi.StringPtrInput
	// cmd
	Cmds pulumi.StringArrayInput
	// cpu count
	Cpus pulumi.IntPtrInput
	// cpu type
	Cputype pulumi.StringPtrInput
	// image entrypoint
	Entrypoints pulumi.StringArrayInput
	// Optional environment variables, keys and values must be strings
	Env pulumi.StringMapInput
	// exec command
	Execs pulumi.StringArrayInput
	// docker image
	Image pulumi.StringPtrInput
	// memory mb
	Memorymb pulumi.IntPtrInput
	// Volume mounts
	Mounts MachineMountArrayInput
	// machine name
	Name pulumi.StringPtrInput
	// Private IP
	Privateip pulumi.StringPtrInput
	// machine region
	Region pulumi.StringPtrInput
	// services
	Services MachineServiceArrayInput
}

func (MachineState) ElementType() reflect.Type {
	return reflect.TypeOf((*machineState)(nil)).Elem()
}

type machineArgs struct {
	// fly app
	App string `pulumi:"app"`
	// cmd
	Cmds []string `pulumi:"cmds"`
	// cpu count
	Cpus *int `pulumi:"cpus"`
	// cpu type
	Cputype *string `pulumi:"cputype"`
	// image entrypoint
	Entrypoints []string `pulumi:"entrypoints"`
	// Optional environment variables, keys and values must be strings
	Env map[string]string `pulumi:"env"`
	// exec command
	Execs []string `pulumi:"execs"`
	// docker image
	Image string `pulumi:"image"`
	// memory mb
	Memorymb *int `pulumi:"memorymb"`
	// Volume mounts
	Mounts []MachineMount `pulumi:"mounts"`
	// machine name
	Name *string `pulumi:"name"`
	// machine region
	Region string `pulumi:"region"`
	// services
	Services []MachineService `pulumi:"services"`
}

// The set of arguments for constructing a Machine resource.
type MachineArgs struct {
	// fly app
	App pulumi.StringInput
	// cmd
	Cmds pulumi.StringArrayInput
	// cpu count
	Cpus pulumi.IntPtrInput
	// cpu type
	Cputype pulumi.StringPtrInput
	// image entrypoint
	Entrypoints pulumi.StringArrayInput
	// Optional environment variables, keys and values must be strings
	Env pulumi.StringMapInput
	// exec command
	Execs pulumi.StringArrayInput
	// docker image
	Image pulumi.StringInput
	// memory mb
	Memorymb pulumi.IntPtrInput
	// Volume mounts
	Mounts MachineMountArrayInput
	// machine name
	Name pulumi.StringPtrInput
	// machine region
	Region pulumi.StringInput
	// services
	Services MachineServiceArrayInput
}

func (MachineArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*machineArgs)(nil)).Elem()
}

type MachineInput interface {
	pulumi.Input

	ToMachineOutput() MachineOutput
	ToMachineOutputWithContext(ctx context.Context) MachineOutput
}

func (*Machine) ElementType() reflect.Type {
	return reflect.TypeOf((**Machine)(nil)).Elem()
}

func (i *Machine) ToMachineOutput() MachineOutput {
	return i.ToMachineOutputWithContext(context.Background())
}

func (i *Machine) ToMachineOutputWithContext(ctx context.Context) MachineOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachineOutput)
}

// MachineArrayInput is an input type that accepts MachineArray and MachineArrayOutput values.
// You can construct a concrete instance of `MachineArrayInput` via:
//
//	MachineArray{ MachineArgs{...} }
type MachineArrayInput interface {
	pulumi.Input

	ToMachineArrayOutput() MachineArrayOutput
	ToMachineArrayOutputWithContext(context.Context) MachineArrayOutput
}

type MachineArray []MachineInput

func (MachineArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Machine)(nil)).Elem()
}

func (i MachineArray) ToMachineArrayOutput() MachineArrayOutput {
	return i.ToMachineArrayOutputWithContext(context.Background())
}

func (i MachineArray) ToMachineArrayOutputWithContext(ctx context.Context) MachineArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachineArrayOutput)
}

// MachineMapInput is an input type that accepts MachineMap and MachineMapOutput values.
// You can construct a concrete instance of `MachineMapInput` via:
//
//	MachineMap{ "key": MachineArgs{...} }
type MachineMapInput interface {
	pulumi.Input

	ToMachineMapOutput() MachineMapOutput
	ToMachineMapOutputWithContext(context.Context) MachineMapOutput
}

type MachineMap map[string]MachineInput

func (MachineMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Machine)(nil)).Elem()
}

func (i MachineMap) ToMachineMapOutput() MachineMapOutput {
	return i.ToMachineMapOutputWithContext(context.Background())
}

func (i MachineMap) ToMachineMapOutputWithContext(ctx context.Context) MachineMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachineMapOutput)
}

type MachineOutput struct{ *pulumi.OutputState }

func (MachineOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Machine)(nil)).Elem()
}

func (o MachineOutput) ToMachineOutput() MachineOutput {
	return o
}

func (o MachineOutput) ToMachineOutputWithContext(ctx context.Context) MachineOutput {
	return o
}

// fly app
func (o MachineOutput) App() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.App }).(pulumi.StringOutput)
}

// cmd
func (o MachineOutput) Cmds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringArrayOutput { return v.Cmds }).(pulumi.StringArrayOutput)
}

// cpu count
func (o MachineOutput) Cpus() pulumi.IntOutput {
	return o.ApplyT(func(v *Machine) pulumi.IntOutput { return v.Cpus }).(pulumi.IntOutput)
}

// cpu type
func (o MachineOutput) Cputype() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.Cputype }).(pulumi.StringOutput)
}

// image entrypoint
func (o MachineOutput) Entrypoints() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringArrayOutput { return v.Entrypoints }).(pulumi.StringArrayOutput)
}

// Optional environment variables, keys and values must be strings
func (o MachineOutput) Env() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringMapOutput { return v.Env }).(pulumi.StringMapOutput)
}

// exec command
func (o MachineOutput) Execs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringArrayOutput { return v.Execs }).(pulumi.StringArrayOutput)
}

// docker image
func (o MachineOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.Image }).(pulumi.StringOutput)
}

// memory mb
func (o MachineOutput) Memorymb() pulumi.IntOutput {
	return o.ApplyT(func(v *Machine) pulumi.IntOutput { return v.Memorymb }).(pulumi.IntOutput)
}

// Volume mounts
func (o MachineOutput) Mounts() MachineMountArrayOutput {
	return o.ApplyT(func(v *Machine) MachineMountArrayOutput { return v.Mounts }).(MachineMountArrayOutput)
}

// machine name
func (o MachineOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Private IP
func (o MachineOutput) Privateip() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.Privateip }).(pulumi.StringOutput)
}

// machine region
func (o MachineOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// services
func (o MachineOutput) Services() MachineServiceArrayOutput {
	return o.ApplyT(func(v *Machine) MachineServiceArrayOutput { return v.Services }).(MachineServiceArrayOutput)
}

type MachineArrayOutput struct{ *pulumi.OutputState }

func (MachineArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Machine)(nil)).Elem()
}

func (o MachineArrayOutput) ToMachineArrayOutput() MachineArrayOutput {
	return o
}

func (o MachineArrayOutput) ToMachineArrayOutputWithContext(ctx context.Context) MachineArrayOutput {
	return o
}

func (o MachineArrayOutput) Index(i pulumi.IntInput) MachineOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Machine {
		return vs[0].([]*Machine)[vs[1].(int)]
	}).(MachineOutput)
}

type MachineMapOutput struct{ *pulumi.OutputState }

func (MachineMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Machine)(nil)).Elem()
}

func (o MachineMapOutput) ToMachineMapOutput() MachineMapOutput {
	return o
}

func (o MachineMapOutput) ToMachineMapOutputWithContext(ctx context.Context) MachineMapOutput {
	return o
}

func (o MachineMapOutput) MapIndex(k pulumi.StringInput) MachineOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Machine {
		return vs[0].(map[string]*Machine)[vs[1].(string)]
	}).(MachineOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MachineInput)(nil)).Elem(), &Machine{})
	pulumi.RegisterInputType(reflect.TypeOf((*MachineArrayInput)(nil)).Elem(), MachineArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MachineMapInput)(nil)).Elem(), MachineMap{})
	pulumi.RegisterOutputType(MachineOutput{})
	pulumi.RegisterOutputType(MachineArrayOutput{})
	pulumi.RegisterOutputType(MachineMapOutput{})
}
