// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Fly.Outputs
{

    [OutputType]
    public sealed class MachineServicePort
    {
        public readonly ImmutableArray<string> Handlers;
        public readonly int Port;

        [OutputConstructor]
        private MachineServicePort(
            ImmutableArray<string> handlers,

            int port)
        {
            Handlers = handlers;
            Port = port;
        }
    }
}
