// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Fly.Outputs
{

    [OutputType]
    public sealed class MachineServicePort
    {
        /// <summary>
        /// Automatically redirect to HTTPS on "http" handler
        /// </summary>
        public readonly bool? ForceHttps;
        /// <summary>
        /// How the edge should process requests; ex empty, or `tls` to attach app's certificate
        /// </summary>
        public readonly ImmutableArray<string> Handlers;
        /// <summary>
        /// Mapped external port number
        /// </summary>
        public readonly int Port;

        [OutputConstructor]
        private MachineServicePort(
            bool? forceHttps,

            ImmutableArray<string> handlers,

            int port)
        {
            ForceHttps = forceHttps;
            Handlers = handlers;
            Port = port;
        }
    }
}
