// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Fly.Outputs
{

    [OutputType]
    public sealed class MachineMount
    {
        public readonly bool? Encrypted;
        /// <summary>
        /// Path for volume to be mounted on vm
        /// </summary>
        public readonly string Path;
        public readonly int? SizeGb;
        /// <summary>
        /// Name or ID of volume
        /// </summary>
        public readonly string Volume;

        [OutputConstructor]
        private MachineMount(
            bool? encrypted,

            string path,

            int? sizeGb,

            string volume)
        {
            Encrypted = encrypted;
            Path = path;
            SizeGb = sizeGb;
            Volume = volume;
        }
    }
}
