// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Fly.Outputs
{

    [OutputType]
    public sealed class MachineServicePort
    {
        /// <summary>
        /// For a port range, the last port to listen on
        /// </summary>
        public readonly int? EndPort;
        /// <summary>
        /// Automatically redirect to HTTPS on "http" handler
        /// </summary>
        public readonly bool? ForceHttps;
        /// <summary>
        /// How the edge should process requests; ex empty, or `tls` to attach app's certificate
        /// </summary>
        public readonly ImmutableArray<string> Handlers;
        /// <summary>
        /// Mapped external port number, either `port` or `start_port` and `end_port` must be set.
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// For a port range, the first port to listen on.
        /// </summary>
        public readonly int? StartPort;

        [OutputConstructor]
        private MachineServicePort(
            int? endPort,

            bool? forceHttps,

            ImmutableArray<string> handlers,

            int? port,

            int? startPort)
        {
            EndPort = endPort;
            ForceHttps = forceHttps;
            Handlers = handlers;
            Port = port;
            StartPort = startPort;
        }
    }
}
