# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

flyApiToken: Optional[str]
"""
fly.io api token. If not set checks env for FLY_API_TOKEN
"""

flyHttpEndpoint: Optional[str]
"""
Where the provider should look to find the fly http endpoint
"""

