# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

flyApiToken: Optional[str]
"""
fly.io api token. If not set checks env for FLY_API_TOKEN
"""

flyHttpEndpoint: Optional[str]
"""
Where the provider should look to find the fly http endpoint
"""

