// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface MachineMount {
    /**
     * Path for volume to be mounted on vm, ex: `/data`
     */
    path: pulumi.Input<string>;
    /**
     * ID of volume
     */
    volume: pulumi.Input<string>;
}

export interface MachineService {
    /**
     * Port the machine listens on
     */
    internalPort: pulumi.Input<number>;
    /**
     * How the port is exposed
     */
    ports: pulumi.Input<pulumi.Input<inputs.MachineServicePort>[]>;
    /**
     * `udp` or `tcp`
     */
    protocol: pulumi.Input<string>;
}

export interface MachineServicePort {
    /**
     * For a port range, the last port to listen on
     */
    endPort?: pulumi.Input<number>;
    /**
     * Automatically redirect to HTTPS on "http" handler
     */
    forceHttps?: pulumi.Input<boolean>;
    /**
     * How the edge should process requests; ex empty, or `tls` to attach app's certificate
     */
    handlers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Mapped external port number, either `port` or `startPort` and `endPort` must be set.
     */
    port?: pulumi.Input<number>;
    /**
     * For a port range, the first port to listen on.
     */
    startPort?: pulumi.Input<number>;
}
