// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface MachineMount {
    encrypted?: pulumi.Input<boolean>;
    /**
     * Path for volume to be mounted on vm
     */
    path: pulumi.Input<string>;
    sizeGb?: pulumi.Input<number>;
    /**
     * Name or ID of volume
     */
    volume: pulumi.Input<string>;
}

export interface MachineService {
    /**
     * Port application listens on internally
     */
    internalPort: pulumi.Input<number>;
    /**
     * External ports and handlers
     */
    ports: pulumi.Input<pulumi.Input<inputs.MachineServicePort>[]>;
    /**
     * network protocol
     */
    protocol: pulumi.Input<string>;
}

export interface MachineServicePort {
    handlers?: pulumi.Input<pulumi.Input<string>[]>;
    port: pulumi.Input<number>;
}
