// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Fly.Inputs
{

    public sealed class MachineServiceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Port the machine listens on
        /// </summary>
        [Input("internalPort", required: true)]
        public Input<int> InternalPort { get; set; } = null!;

        [Input("ports", required: true)]
        private InputList<Inputs.MachineServicePortGetArgs>? _ports;

        /// <summary>
        /// How the port is exposed
        /// </summary>
        public InputList<Inputs.MachineServicePortGetArgs> Ports
        {
            get => _ports ?? (_ports = new InputList<Inputs.MachineServicePortGetArgs>());
            set => _ports = value;
        }

        /// <summary>
        /// `udp` or `tcp`
        /// </summary>
        [Input("protocol", required: true)]
        public Input<string> Protocol { get; set; } = null!;

        public MachineServiceGetArgs()
        {
        }
        public static new MachineServiceGetArgs Empty => new MachineServiceGetArgs();
    }
}
