env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  upgrade_provider:
    if: ${{ (contains(github.event.issue.title, 'Upgrade terraform-provider-')) || github.event_name == 'workflow_dispatch' }}
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@a1d9f03fbfd923f787427c1d9e99c2356711d483 # v0.0.13
      with:
        kind: all
        email: botdirien.de
        username: dirien-bot
name: Upgrade provider

permissions:
  contents: write

on:
  issues:
    types:
    - opened
  workflow_dispatch: {}
