// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieve info about graphql app
 *
 * ## Example Usage
 */
export function getApp(args: GetAppArgs, opts?: pulumi.InvokeOptions): Promise<GetAppResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly:index/getApp:getApp", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getApp.
 */
export interface GetAppArgs {
    /**
     * Name of app
     */
    name: string;
}

/**
 * A collection of values returned by getApp.
 */
export interface GetAppResult {
    readonly appurl: string;
    readonly currentrelease: string;
    readonly deployed: boolean;
    readonly healthchecks: string[];
    readonly hostname: string;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    readonly ipaddresses: string[];
    /**
     * Name of app
     */
    readonly name: string;
    readonly status: string;
}
/**
 * Retrieve info about graphql app
 *
 * ## Example Usage
 */
export function getAppOutput(args: GetAppOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAppResult> {
    return pulumi.output(args).apply((a: any) => getApp(a, opts))
}

/**
 * A collection of arguments for invoking getApp.
 */
export interface GetAppOutputArgs {
    /**
     * Name of app
     */
    name: pulumi.Input<string>;
}
