// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Fly certificate data source
 */
export function getCert(args: GetCertArgs, opts?: pulumi.InvokeOptions): Promise<GetCertResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly:index/getCert:getCert", {
        "app": args.app,
        "hostname": args.hostname,
    }, opts);
}

/**
 * A collection of arguments for invoking getCert.
 */
export interface GetCertArgs {
    /**
     * Name of app attached to
     */
    app: string;
    /**
     * hostname
     */
    hostname: string;
}

/**
 * A collection of values returned by getCert.
 */
export interface GetCertResult {
    /**
     * Name of app attached to
     */
    readonly app: string;
    /**
     * check
     */
    readonly check: boolean;
    /**
     * DnsValidationHostname
     */
    readonly dnsvalidationhostname: string;
    /**
     * DnsValidationHostname
     */
    readonly dnsvalidationinstructions: string;
    /**
     * DnsValidationTarget
     */
    readonly dnsvalidationtarget: string;
    /**
     * hostname
     */
    readonly hostname: string;
    /**
     * ID of certificate
     */
    readonly id: string;
}
/**
 * Fly certificate data source
 */
export function getCertOutput(args: GetCertOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCertResult> {
    return pulumi.output(args).apply((a: any) => getCert(a, opts))
}

/**
 * A collection of arguments for invoking getCert.
 */
export interface GetCertOutputArgs {
    /**
     * Name of app attached to
     */
    app: pulumi.Input<string>;
    /**
     * hostname
     */
    hostname: pulumi.Input<string>;
}
