// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCert(args: GetCertArgs, opts?: pulumi.InvokeOptions): Promise<GetCertResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly:index/getCert:getCert", {
        "app": args.app,
        "hostname": args.hostname,
    }, opts);
}

/**
 * A collection of arguments for invoking getCert.
 */
export interface GetCertArgs {
    /**
     * The App this resource will be created in
     */
    app: string;
    hostname: string;
}

/**
 * A collection of values returned by getCert.
 */
export interface GetCertResult {
    /**
     * The App this resource will be created in
     */
    readonly app: string;
    readonly check: boolean;
    readonly dnsValidationHostname: string;
    readonly dnsValidationInstructions: string;
    readonly dnsValidationTarget: string;
    readonly hostname: string;
    /**
     * A fly-generated ID
     */
    readonly id: string;
}
export function getCertOutput(args: GetCertOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCertResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fly:index/getCert:getCert", {
        "app": args.app,
        "hostname": args.hostname,
    }, opts);
}

/**
 * A collection of arguments for invoking getCert.
 */
export interface GetCertOutputArgs {
    /**
     * The App this resource will be created in
     */
    app: pulumi.Input<string>;
    hostname: pulumi.Input<string>;
}
