// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getIp(args: GetIpArgs, opts?: pulumi.InvokeOptions): Promise<GetIpResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly:index/getIp:getIp", {
        "app": args.app,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getIp.
 */
export interface GetIpArgs {
    /**
     * The App this resource will be created in
     */
    app: string;
    /**
     * A fly-generated ID
     */
    id: string;
}

/**
 * A collection of values returned by getIp.
 */
export interface GetIpResult {
    /**
     * Empty if using `sharedV4`
     */
    readonly address: string;
    /**
     * The App this resource will be created in
     */
    readonly app: string;
    /**
     * A fly-generated ID
     */
    readonly id: string;
    /**
     * Fly region, ex `ord`, `sin`, `mad`
     */
    readonly region: string;
    /**
     * `v4`, `v6`, or `privateV6`
     */
    readonly type: string;
}
export function getIpOutput(args: GetIpOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIpResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fly:index/getIp:getIp", {
        "app": args.app,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getIp.
 */
export interface GetIpOutputArgs {
    /**
     * The App this resource will be created in
     */
    app: pulumi.Input<string>;
    /**
     * A fly-generated ID
     */
    id: pulumi.Input<string>;
}
