// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Volume extends pulumi.CustomResource {
    /**
     * Get an existing Volume resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VolumeState, opts?: pulumi.CustomResourceOptions): Volume {
        return new Volume(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fly:index/volume:Volume';

    /**
     * Returns true if the given object is an instance of Volume.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Volume {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Volume.__pulumiType;
    }

    /**
     * The App this resource will be created in
     */
    declare public readonly app: pulumi.Output<string>;
    declare public readonly encrypted: pulumi.Output<boolean>;
    /**
     * A user-provided identifier
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Fly region, ex `ord`, `sin`, `mad`
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * Size of volume in GB
     */
    declare public readonly size: pulumi.Output<number>;

    /**
     * Create a Volume resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VolumeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VolumeArgs | VolumeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VolumeState | undefined;
            resourceInputs["app"] = state?.app;
            resourceInputs["encrypted"] = state?.encrypted;
            resourceInputs["name"] = state?.name;
            resourceInputs["region"] = state?.region;
            resourceInputs["size"] = state?.size;
        } else {
            const args = argsOrState as VolumeArgs | undefined;
            if (args?.app === undefined && !opts.urn) {
                throw new Error("Missing required property 'app'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.size === undefined && !opts.urn) {
                throw new Error("Missing required property 'size'");
            }
            resourceInputs["app"] = args?.app;
            resourceInputs["encrypted"] = args?.encrypted;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
            resourceInputs["size"] = args?.size;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Volume.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Volume resources.
 */
export interface VolumeState {
    /**
     * The App this resource will be created in
     */
    app?: pulumi.Input<string | undefined>;
    encrypted?: pulumi.Input<boolean | undefined>;
    /**
     * A user-provided identifier
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Fly region, ex `ord`, `sin`, `mad`
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * Size of volume in GB
     */
    size?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a Volume resource.
 */
export interface VolumeArgs {
    /**
     * The App this resource will be created in
     */
    app: pulumi.Input<string>;
    encrypted?: pulumi.Input<boolean | undefined>;
    /**
     * A user-provided identifier
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Fly region, ex `ord`, `sin`, `mad`
     */
    region: pulumi.Input<string>;
    /**
     * Size of volume in GB
     */
    size: pulumi.Input<number>;
}
